// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Withdraws only a context-free user message still pending in the named turn.
 * Acceptance telemetry and settings already applied at submission remain unchanged.
 */
export type TurnSteerWithdrawParams = { threadId: string, expectedTurnId: string, clientUserMessageId: string, };
